# Generated by Django 2.2.7 on 2020-09-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shop_items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavour', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='')),
                ('price', models.IntegerField()),
                ('discount', models.IntegerField(default=0)),
            ],
        ),
    ]
