# Generated by Django 2.2.7 on 2020-09-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_items',
            name='image_url',
            field=models.ImageField(max_length=10000, upload_to=''),
        ),
    ]
