# Generated by Django 2.2.7 on 2020-09-19 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200918_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='ordered_item',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='shop_items',
            name='image_url',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
