# Generated by Django 2.2.7 on 2020-09-19 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20200919_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='ordered_item',
            field=models.CharField(default='', max_length=100),
        ),
    ]
