# Generated by Django 2.2.7 on 2020-09-19 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20200919_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_items',
            name='image_url',
            field=models.CharField(max_length=10000),
        ),
    ]
