# Generated by Django 2.2.7 on 2020-09-19 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20200919_1001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop_items',
            old_name='flavour',
            new_name='name_of_item',
        ),
    ]
