# Generated by Django 2.2.7 on 2020-09-19 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20200919_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='phone_number',
            field=models.IntegerField(default=0),
        ),
    ]
